// frontend/src/App.tsx
import { useState } from "react";
import { App as AntdApp, Drawer, Grid, Modal, Input, Space, Button } from "antd";
import { ChatWorkspace } from "./components/ChatWorkspace";
import { DocumentSidebar } from "./components/DocumentSidebar";
import { DocumentDetail } from "./components/DocumentDetail";
import { AuthPanel } from "./components/AuthPanel";
import { CopyOutlined, DownloadOutlined, LinkOutlined } from "@ant-design/icons";
import { useAuthSession } from "./hooks/useAuthSession";
import { useDocumentLibrary } from "./hooks/useDocumentLibrary";
import { useRagConversation } from "./hooks/useRagConversation";

function App() {
  const { message } = AntdApp.useApp();
  const screens = Grid.useBreakpoint();
  const [documentDrawerOpen, setDocumentDrawerOpen] = useState(false);
  const [authDrawerOpen, setAuthDrawerOpen] = useState(false);
  const authSession = useAuthSession(message);
  const documentLibrary = useDocumentLibrary(
    message,
    authSession.authStatus.authenticated,
    authSession.handleUnauthorized
  );
  const conversation = useRagConversation(message);
  const drawerWidth = screens.xl
    ? "32vw"
    : screens.lg
      ? "38vw"
      : screens.md
        ? "46vw"
        : "100vw";

  return (
    <main
      className="relative isolate h-screen min-h-dvh overflow-hidden p-7 max-[1120px]:p-5 max-[720px]:p-3.5 [--message-shell-max:clamp(760px,96%,1440px)] max-[1120px]:[--message-shell-max:min(100%,920px)] max-[720px]:[--message-shell-max:100%]"
    >
      <div
        className="relative z-10 mx-auto flex h-full min-h-0 w-full max-w-[1600px]"
      >
        <ChatWorkspace
          messages={conversation.messages}
          prompt={conversation.prompt}
          maxResults={conversation.maxResults}
          streaming={conversation.streaming}
          authenticated={authSession.authStatus.authenticated}
          authUser={authSession.authStatus.user || null}
          onOpenDocuments={() => setDocumentDrawerOpen(true)}
          onOpenAuth={() => setAuthDrawerOpen(true)}
          onPromptChange={conversation.setPrompt}
          onMaxResultsChange={conversation.setMaxResults}
          onSend={conversation.handleSend}
          onCancel={conversation.handleCancel}
          onClearConversation={conversation.handleClearConversation}
        />
      </div>

      <Drawer
        open={documentDrawerOpen}
        onClose={() => setDocumentDrawerOpen(false)}
        placement="left"
        width={drawerWidth}
        closable={false}
        title={null}
        classNames={{
          mask: "!backdrop-blur-[3px]",
          wrapper: "!shadow-none",
          section: "!bg-[#fffaf4]",
          body: "!h-full !p-0"
        }}
      >
        <DocumentSidebar
          documents={documentLibrary.documents}
          documentsLoading={documentLibrary.documentsLoading}
          uploading={documentLibrary.uploading}
          deletingId={documentLibrary.deletingId}
          uploadProgress={documentLibrary.uploadProgress}
          batchTotal={documentLibrary.batchTotal}
          batchCurrent={documentLibrary.batchCurrent}
          authenticated={authSession.authStatus.authenticated}
          onClose={() => setDocumentDrawerOpen(false)}
          onRefreshDocuments={documentLibrary.refreshDocuments}
          onUpload={documentLibrary.handleUpload}
          onDeleteDocument={documentLibrary.handleDeleteDocument}
          onCancelUpload={documentLibrary.cancelUpload}
          onViewDocument={documentLibrary.handleViewDocument}
          onShowDownloadLink={documentLibrary.handleShowDownloadLink}
        />
      </Drawer>

      <Drawer
        open={!!documentLibrary.viewingDocument}
        onClose={documentLibrary.handleCloseDocumentDetail}
        placement="left"
        width={drawerWidth}
        closable={false}
        title={null}
        classNames={{
          mask: "!backdrop-blur-[3px]",
          wrapper: "!shadow-none",
          section: "!bg-[#fffaf4]",
          body: "!h-full !p-0"
        }}
      >
        <DocumentDetail
          detail={documentLibrary.viewingDocument}
          loading={documentLibrary.viewingLoading}
          onClose={documentLibrary.handleCloseDocumentDetail}
          onDownload={documentLibrary.handleShowDownloadLink}
        />
      </Drawer>

      <Modal
        open={!!documentLibrary.downloadLinkInfo}
        onCancel={documentLibrary.handleCloseDownloadLink}
        footer={null}
        closable={false}
        width={420}
        title={null}
      >
        {documentLibrary.downloadLinkInfo && (
          <div className="py-2">
            <div className="mb-3 flex items-start gap-2">
              <LinkOutlined className="mt-1 text-accent-500" />
              <div className="min-w-0">
                <p className="text-sm font-medium text-ink-900">
                  下载链接
                </p>
                <p className="truncate text-xs text-ink-500">
                  {documentLibrary.downloadLinkInfo.filename}
                </p>
              </div>
            </div>
            <Space.Compact className="w-full">
              <Input
                readOnly
                value={documentLibrary.downloadLinkInfo!.downloadUrl}
                className="bg-ink-50"
              />
              <Button
                icon={<CopyOutlined />}
                onClick={() => {
                  navigator.clipboard.writeText(documentLibrary.downloadLinkInfo!.downloadUrl);
                  message.success("链接已复制到剪贴板");
                }}
              >
                复制
              </Button>
              <Button
                type="primary"
                icon={<DownloadOutlined />}
                onClick={() => {
                  const link = document.createElement("a");
                  link.href = documentLibrary.downloadLinkInfo!.downloadUrl;
                  link.download = documentLibrary.downloadLinkInfo!.filename;
                  link.style.display = "none";
                  document.body.appendChild(link);
                  link.click();
                  document.body.removeChild(link);
                }}
              >
                下载
              </Button>
            </Space.Compact>
            <p className="mt-2 text-xs text-ink-500">
              点击"下载"按钮将触发文件下载（部分浏览器可能不支持）
            </p>
          </div>
        )}
      </Modal>

      <Drawer
        open={authDrawerOpen}
        onClose={() => setAuthDrawerOpen(false)}
        placement="right"
        width={drawerWidth}
        closable={false}
        title={null}
        classNames={{
          mask: "!backdrop-blur-[3px]",
          wrapper: "!shadow-none",
          section: "!bg-[#fffaf4]",
          body: "!h-full !p-0"
        }}
      >
        <AuthPanel
          authenticated={authSession.authStatus.authenticated}
          authLoading={authSession.authLoading}
          authSubmitting={authSession.authSubmitting}
          authUser={authSession.authStatus.user || null}
          registrationCodes={authSession.registrationCodes}
          registrationCodesLoading={authSession.registrationCodesLoading}
          codeCreating={authSession.codeCreating}
          codeMutatingId={authSession.codeMutatingId}
          onClose={() => setAuthDrawerOpen(false)}
          onLogin={authSession.handleLogin}
          onRegister={authSession.handleRegister}
          onLogout={authSession.handleLogout}
          onRefreshRegistrationCodes={authSession.refreshRegistrationCodes}
          onCreateRegistrationCode={authSession.handleCreateRegistrationCode}
          onDisableRegistrationCode={authSession.handleDisableRegistrationCode}
          onDeleteRegistrationCode={authSession.handleDeleteRegistrationCode}
        />
      </Drawer>
    </main>
  );
}

export default App;

// front-vue/src/App.vue
<template>
  <a-config-provider :locale="zhCN" :theme="theme">
    <a-app>
      <main
        class="relative isolate h-screen min-h-dvh overflow-hidden p-7 max-[1120px]:p-5 max-[720px]:p-3.5 [--message-shell-max:clamp(760px,96%,1440px)] max-[1120px]:[--message-shell-max:min(100%,920px)] max-[720px]:[--message-shell-max:100%]"
      >
        <div class="relative z-10 mx-auto flex h-full min-h-0 w-full max-w-[1600px]">
          <ChatWorkspace
            :messages="messages"
            :prompt="prompt"
            :max-results="maxResults"
            :streaming="streaming"
            :authenticated="authStatus.authenticated"
            :auth-user="authStatus.user || null"
            @open-documents="documentDrawerOpen = true"
            @open-auth="authDrawerOpen = true"
            @update:prompt="setPrompt"
            @update:max-results="setMaxResults"
            @send="handleSend"
            @cancel="handleCancel"
            @clear-conversation="handleClearConversation"
          />
        </div>

        <!-- Document Drawer -->
        <a-drawer
          v-model:open="documentDrawerOpen"
          placement="left"
          :width="documentDrawerWidth"
          :closable="false"
          :title="null"
          :body-style="{ padding: 0, height: '100%' }"
          :mask-style="{ backdropFilter: 'blur(3px)' }"
        >
          <DocumentSidebar
            :documents="documents"
            :documents-loading="documentsLoading"
            :uploading="uploading"
            :upload-progress="uploadProgress"
            :deleting-id="deletingId"
            :rag-health="ragHealth"
            :document-health="documentHealth"
            :refreshing-health="refreshingHealth"
            :authenticated="authStatus.authenticated"
            @close="documentDrawerOpen = false"
            @refresh-documents="handleRefreshDocuments"
            @refresh-health="handleRefreshHealth"
            @upload="handleUpload"
            @cancel-upload="cancelUpload"
            @delete-document="handleDeleteDocument"
            @view-document="handleViewDocument"
            @download-document="handleDownloadDocument"
          />
        </a-drawer>

        <!-- Document Detail Drawer -->
        <a-drawer
          :open="!!viewingDocument"
          placement="left"
          :width="documentDrawerWidth"
          :closable="false"
          :title="null"
          :body-style="{ padding: 0, height: '100%' }"
          :mask-style="{ backdropFilter: 'blur(3px)' }"
          @close="handleCloseDocumentDetail"
        >
          <DocumentDetail
            :detail="viewingDocument"
            :loading="viewingLoading"
            @close="handleCloseDocumentDetail"
            @download="handleDownloadDocument"
          />
        </a-drawer>

        <!-- Auth Drawer -->
        <a-drawer
          v-model:open="authDrawerOpen"
          placement="right"
          :width="authDrawerWidth"
          :closable="false"
          :title="null"
          :body-style="{ padding: 0, height: '100%' }"
          :mask-style="{ backdropFilter: 'blur(3px)' }"
        >
          <AuthPanel
            :auth-status="authStatus"
            :auth-submitting="authSubmitting"
            :registration-codes="registrationCodes"
            :registration-codes-loading="registrationCodesLoading"
            :code-creating="codeCreating"
            :code-mutating-id="codeMutatingId"
            @close="authDrawerOpen = false"
            @login="handleLogin"
            @register="handleRegister"
            @logout="handleLogout"
            @create-code="handleCreateRegistrationCode"
            @disable-code="handleDisableRegistrationCode"
            @delete-code="handleDeleteRegistrationCode"
          />
        </a-drawer>
      </main>
    </a-app>
  </a-config-provider>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { message } from "ant-design-vue";
import zhCN from "ant-design-vue/es/locale/zh_CN";
import ChatWorkspace from "./components/ChatWorkspace.vue";
import DocumentSidebar from "./components/DocumentSidebar.vue";
import DocumentDetail from "./components/DocumentDetail.vue";
import AuthPanel from "./components/AuthPanel.vue";
import { useDocumentLibrary } from "./composables/useDocumentLibrary";
import { useRagConversation } from "./composables/useRagConversation";
import { useServiceHealth } from "./composables/useServiceHealth";
import { useAuthSession } from "./composables/useAuthSession";
import { useViewportWidth } from "./composables/useViewportWidth";

const theme = {
  token: {
    colorPrimary: "#f25b2a",
    colorInfo: "#f25b2a",
    colorSuccess: "#1d8f6f",
    borderRadius: 22,
    fontFamily:
      '"Space Grotesk", "Noto Sans SC", "Segoe UI", "PingFang SC", sans-serif'
  }
};

const documentDrawerOpen = ref(false);
const authDrawerOpen = ref(false);
const { width } = useViewportWidth();

const documentDrawerWidth = computed(() => {
  if (width.value >= 1200) return "32vw";
  if (width.value >= 992) return "38vw";
  if (width.value >= 768) return "46vw";
  return "100vw";
});

const authDrawerWidth = computed(() => {
  if (width.value >= 768) return "420px";
  return "100vw";
});

// Auth session
const {
  authStatus,
  authSubmitting,
  registrationCodes,
  registrationCodesLoading,
  codeCreating,
  codeMutatingId,
  refreshSession,
  refreshRegistrationCodes,
  handleLogin,
  handleRegister,
  handleLogout,
  handleCreateRegistrationCode,
  handleDisableRegistrationCode,
  handleDeleteRegistrationCode
} = useAuthSession(message);

// Document library
const {
  documents,
  documentsLoading,
  uploading,
  uploadProgress,
  deletingId,
  refreshDocuments,
  handleUpload,
  cancelUpload,
  handleDeleteDocument,
  handleViewDocument,
  handleDownloadDocument,
  viewingDocument,
  viewingLoading,
  handleCloseDocumentDetail
} = useDocumentLibrary(message, authStatus.authenticated, async () => {
  await refreshSession(false);
});

// RAG conversation
const {
  messages,
  prompt,
  setPrompt,
  maxResults,
  setMaxResults,
  streaming,
  handleSend,
  handleCancel,
  handleClearConversation
} = useRagConversation(message);

// Service health
const {
  ragHealth,
  documentHealth,
  refreshingHealth,
  refreshHealth
} = useServiceHealth();

// Handler wrappers
function handleRefreshDocuments() {
  void refreshDocuments();
}

function handleRefreshHealth() {
  void refreshHealth();
}
</script>
