// front-vue/src/components/admin/RoleManagement.vue
<template>
  <div class="flex h-full flex-col">
    <div class="mb-4 flex items-center justify-between">
      <h2 class="text-lg font-bold uppercase tracking-wider text-ink-950">角色管理</h2>
      <a-space>
        <a-button :loading="loading" @click="fetchRoles">
          <template #icon><ReloadOutlined /></template>
          刷新
        </a-button>
        <a-button type="primary" @click="openCreateModal">
          <template #icon><PlusOutlined /></template>
          创建角色
        </a-button>
      </a-space>
    </div>

    <a-spin :spinning="loading">
      <div class="border border-ink-300">
        <a-table
          row-key="id"
          :columns="columns"
          :data-source="roles"
          :pagination="{ pageSize: 10, showSizeChanger: true, showTotal: (total: number) => `共 ${total} 条` }"
          :locale="{ emptyText: '暂无角色数据' }"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.dataIndex === 'code'">
              <a-tag :color="isBuiltinRole(record.code) ? 'red' : 'default'">{{ record.code }}</a-tag>
            </template>
            <template v-else-if="column.dataIndex === 'permissions'">
              <span v-if="record.permissions.length > 0" class="flex flex-wrap gap-1">
                <a-tag v-for="p in record.permissions" :key="p.id" color="blue">{{ p.name }}</a-tag>
              </span>
              <a-tag v-else>无权限</a-tag>
            </template>
            <template v-else-if="column.key === 'actions'">
              <a-space size="small">
                <a-button size="small" @click="openEditModal(record)">编辑</a-button>
                <a-tooltip v-if="isBuiltinRole(record.code)" title="内置角色不可删除">
                  <a-button size="small" danger disabled>删除</a-button>
                </a-tooltip>
                <a-popconfirm
                  v-else
                  title="确认删除该角色？"
                  description="此操作不可撤销"
                  @confirm="handleDelete(record.id)"
                >
                  <a-button size="small" danger>删除</a-button>
                </a-popconfirm>
              </a-space>
            </template>
          </template>
        </a-table>
      </div>
    </a-spin>

    <!-- Create Role Modal -->
    <a-modal
      v-model:open="createModalOpen"
      title="创建角色"
      :confirm-loading="createLoading"
      ok-text="创建"
      cancel-text="取消"
      @ok="handleCreate"
      @cancel="resetCreateForm"
    >
      <div class="flex flex-col gap-4 py-2">
        <div>
          <label class="mb-1 block text-sm font-medium text-ink-700">角色编码</label>
          <a-input v-model:value="createForm.code" placeholder="如: EDITOR" />
        </div>
        <div>
          <label class="mb-1 block text-sm font-medium text-ink-700">角色名称</label>
          <a-input v-model:value="createForm.name" placeholder="如: 编辑员" />
        </div>
        <div>
          <label class="mb-1 block text-sm font-medium text-ink-700">描述</label>
          <a-input v-model:value="createForm.description" placeholder="角色描述（可选）" />
        </div>
        <div>
          <label class="mb-1 block text-sm font-medium text-ink-700">权限</label>
          <a-select
            v-model:value="createForm.permissionIds"
            mode="multiple"
            class="w-full"
            placeholder="选择权限"
            :options="permissionOptions"
          />
        </div>
      </div>
    </a-modal>

    <!-- Edit Role Modal -->
    <a-modal
      v-model:open="editModalOpen"
      title="编辑角色"
      :confirm-loading="editLoading"
      ok-text="保存"
      cancel-text="取消"
      @ok="handleEdit"
      @cancel="closeEditModal"
    >
      <div v-if="editingRole" class="flex flex-col gap-4 py-2">
        <div>
          <label class="mb-1 block text-sm font-medium text-ink-700">角色名称</label>
          <a-input v-model:value="editingRole.name" />
        </div>
        <div>
          <label class="mb-1 block text-sm font-medium text-ink-700">描述</label>
          <a-input v-model:value="editingRole.description" />
        </div>
        <div>
          <label class="mb-1 block text-sm font-medium text-ink-700">权限</label>
          <a-select
            v-model:value="editingRole.permissionIds"
            mode="multiple"
            class="w-full"
            placeholder="选择权限"
            :options="permissionOptions"
          />
        </div>
      </div>
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { message } from "ant-design-vue";
import { ReloadOutlined, PlusOutlined } from "@ant-design/icons-vue";
import type { TableColumnType } from "ant-design-vue";
import {
  listRoles,
  createRole,
  updateRole,
  deleteRole,
  listPermissions,
} from "../../lib/adminApi";
import type { Role, Permission, CreateRoleRequest } from "../../types/admin";

const BUILTIN_ROLES = new Set(["SUPER_ADMIN", "ADMIN", "USER"]);

const roles = ref<Role[]>([]);
const permissions = ref<Permission[]>([]);
const loading = ref(false);

const createModalOpen = ref(false);
const createLoading = ref(false);
const createForm = ref<CreateRoleRequest>({
  code: "",
  name: "",
  description: "",
  permissionIds: [],
});

const editModalOpen = ref(false);
const editLoading = ref(false);
const editingRole = ref<{
  id: number;
  name: string;
  description: string;
  permissionIds: number[];
} | null>(null);

const permissionOptions = ref<{ label: string; value: number }[]>([]);

const columns: TableColumnType[] = [
  { title: "ID", dataIndex: "id", key: "id", width: 64 },
  { title: "编码", dataIndex: "code", key: "code" },
  { title: "名称", dataIndex: "name", key: "name" },
  { title: "描述", dataIndex: "description", key: "description", ellipsis: true },
  { title: "权限", dataIndex: "permissions", key: "permissions", width: 280 },
  { title: "操作", key: "actions", width: 160 },
];

function isBuiltinRole(code: string): boolean {
  return BUILTIN_ROLES.has(code);
}

async function fetchRoles() {
  loading.value = true;
  try {
    roles.value = await listRoles();
  } catch (err) {
    message.error(err instanceof Error ? err.message : "加载角色列表失败");
  } finally {
    loading.value = false;
  }
}

async function fetchPermissions() {
  try {
    const result = await listPermissions();
    permissions.value = result;
    permissionOptions.value = result.map((p) => ({
      label: `${p.name} (${p.code})`,
      value: p.id,
    }));
  } catch {
    // Permissions are supplementary; don't block the UI on failure
  }
}

function openCreateModal() {
  createForm.value = { code: "", name: "", description: "", permissionIds: [] };
  createModalOpen.value = true;
}

function resetCreateForm() {
  createForm.value = { code: "", name: "", description: "", permissionIds: [] };
}

async function handleCreate() {
  if (!createForm.value.code.trim() || !createForm.value.name.trim()) {
    message.warning("请填写角色编码和名称");
    return;
  }
  createLoading.value = true;
  try {
    await createRole(createForm.value);
    message.success("角色创建成功");
    createModalOpen.value = false;
    createForm.value = { code: "", name: "", description: "", permissionIds: [] };
    await fetchRoles();
  } catch (err) {
    message.error(err instanceof Error ? err.message : "创建角色失败");
  } finally {
    createLoading.value = false;
  }
}

function openEditModal(record: Role) {
  editingRole.value = {
    id: record.id,
    name: record.name,
    description: record.description,
    permissionIds: record.permissions.map((p) => p.id),
  };
  editModalOpen.value = true;
}

function closeEditModal() {
  editModalOpen.value = false;
  editingRole.value = null;
}

async function handleEdit() {
  if (!editingRole.value) return;
  editLoading.value = true;
  try {
    await updateRole(editingRole.value.id, {
      name: editingRole.value.name,
      description: editingRole.value.description,
      permissionIds: editingRole.value.permissionIds,
    });
    message.success("角色更新成功");
    editModalOpen.value = false;
    editingRole.value = null;
    await fetchRoles();
  } catch (err) {
    message.error(err instanceof Error ? err.message : "更新角色失败");
  } finally {
    editLoading.value = false;
  }
}

async function handleDelete(id: number) {
  try {
    await deleteRole(id);
    message.success("角色已删除");
    await fetchRoles();
  } catch (err) {
    message.error(err instanceof Error ? err.message : "删除角色失败");
  }
}

onMounted(() => {
  fetchRoles();
  fetchPermissions();
});
</script>

// frontend/src/components/admin/RoleManagement.tsx
import { useEffect, useState, useCallback } from "react";
import {
  App as AntdApp,
  Button,
  Input,
  Modal,
  Popconfirm,
  Select,
  Space,
  Spin,
  Table,
  Tag,
  Tooltip,
} from "antd";
import { PlusOutlined, ReloadOutlined } from "@ant-design/icons";
import type { ColumnsType } from "antd/es/table";
import {
  listRoles,
  createRole,
  updateRole,
  deleteRole,
  listPermissions,
} from "../../lib/adminApi";
import type { Role, Permission, CreateRoleRequest, UpdateRoleRequest } from "../../types/admin";

const BUILTIN_ROLES = new Set(["SUPER_ADMIN", "ADMIN", "USER"]);

export function RoleManagement() {
  const { message } = AntdApp.useApp();

  const [roles, setRoles] = useState<Role[]>([]);
  const [permissions, setPermissions] = useState<Permission[]>([]);
  const [loading, setLoading] = useState(false);

  const [createModalOpen, setCreateModalOpen] = useState(false);
  const [createLoading, setCreateLoading] = useState(false);
  const [createForm, setCreateForm] = useState<CreateRoleRequest>({
    code: "",
    name: "",
    description: "",
    permissionIds: [],
  });

  const [editModalOpen, setEditModalOpen] = useState(false);
  const [editLoading, setEditLoading] = useState(false);
  const [editingRole, setEditingRole] = useState<{
    id: number;
    name: string;
    description: string;
    permissionIds: number[];
  } | null>(null);

  const fetchRoles = useCallback(async () => {
    setLoading(true);
    try {
      const result = await listRoles();
      setRoles(result);
    } catch (err) {
      message.error(err instanceof Error ? err.message : "加载角色列表失败");
    } finally {
      setLoading(false);
    }
  }, [message]);

  const fetchPermissions = useCallback(async () => {
    try {
      const result = await listPermissions();
      setPermissions(result);
    } catch {
      // Permissions are supplementary; don't block the UI on failure
    }
  }, []);

  useEffect(() => {
    fetchRoles();
    fetchPermissions();
  }, [fetchRoles, fetchPermissions]);

  const handleCreate = useCallback(async () => {
    if (!createForm.code.trim() || !createForm.name.trim()) {
      message.warning("请填写角色编码和名称");
      return;
    }
    setCreateLoading(true);
    try {
      await createRole(createForm);
      message.success("角色创建成功");
      setCreateModalOpen(false);
      setCreateForm({ code: "", name: "", description: "", permissionIds: [] });
      await fetchRoles();
    } catch (err) {
      message.error(err instanceof Error ? err.message : "创建角色失败");
    } finally {
      setCreateLoading(false);
    }
  }, [createForm, message, fetchRoles]);

  const handleEdit = useCallback(async () => {
    if (!editingRole) return;
    setEditLoading(true);
    try {
      const req: UpdateRoleRequest = {
        name: editingRole.name,
        description: editingRole.description,
        permissionIds: editingRole.permissionIds,
      };
      await updateRole(editingRole.id, req);
      message.success("角色更新成功");
      setEditModalOpen(false);
      setEditingRole(null);
      await fetchRoles();
    } catch (err) {
      message.error(err instanceof Error ? err.message : "更新角色失败");
    } finally {
      setEditLoading(false);
    }
  }, [editingRole, message, fetchRoles]);

  const handleDelete = useCallback(
    async (id: number) => {
      try {
        await deleteRole(id);
        message.success("角色已删除");
        await fetchRoles();
      } catch (err) {
        message.error(err instanceof Error ? err.message : "删除角色失败");
      }
    },
    [message, fetchRoles],
  );

  const columns: ColumnsType<Role> = [
    {
      title: "ID",
      dataIndex: "id",
      key: "id",
      width: 64,
    },
    {
      title: "编码",
      dataIndex: "code",
      key: "code",
      render: (code: string) => (
        <Tag color={BUILTIN_ROLES.has(code) ? "red" : "default"}>{code}</Tag>
      ),
    },
    {
      title: "名称",
      dataIndex: "name",
      key: "name",
    },
    {
      title: "描述",
      dataIndex: "description",
      key: "description",
      ellipsis: true,
    },
    {
      title: "权限",
      dataIndex: "permissions",
      key: "permissions",
      width: 280,
      render: (perms: Permission[]) =>
        perms.length > 0 ? (
          <span className="flex flex-wrap gap-1">
            {perms.map((p) => (
              <Tag key={p.id} color="blue">{p.name}</Tag>
            ))}
          </span>
        ) : (
          <Tag>无权限</Tag>
        ),
    },
    {
      title: "操作",
      key: "actions",
      width: 160,
      render: (_: unknown, record: Role) => (
        <Space size="small">
          <Button
            size="small"
            onClick={() => {
              setEditingRole({
                id: record.id,
                name: record.name,
                description: record.description,
                permissionIds: record.permissions.map((p) => p.id),
              });
              setEditModalOpen(true);
            }}
          >
            编辑
          </Button>
          {BUILTIN_ROLES.has(record.code) ? (
            <Tooltip title="内置角色不可删除">
              <Button size="small" danger disabled>
                删除
              </Button>
            </Tooltip>
          ) : (
            <Popconfirm
              title="确认删除该角色？"
              description="此操作不可撤销"
              onConfirm={() => handleDelete(record.id)}
            >
              <Button size="small" danger>删除</Button>
            </Popconfirm>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div className="flex h-full flex-col">
      <div className="mb-4 flex items-center justify-between">
        <h2 className="text-lg font-bold uppercase tracking-wider text-ink-950">角色管理</h2>
        <Space>
          <Button icon={<ReloadOutlined />} onClick={fetchRoles} loading={loading}>
            刷新
          </Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateModalOpen(true)}>
            创建角色
          </Button>
        </Space>
      </div>

      <Spin spinning={loading}>
        <div className="border border-ink-300">
          <Table<Role>
            rowKey="id"
            columns={columns}
            dataSource={roles}
            pagination={{ pageSize: 10, showSizeChanger: true, showTotal: (t) => `共 ${t} 条` }}
            locale={{ emptyText: "暂无角色数据" }}
          />
        </div>
      </Spin>

      {/* Create Role Modal */}
      <Modal
        open={createModalOpen}
        title="创建角色"
        onCancel={() => {
          setCreateModalOpen(false);
          setCreateForm({ code: "", name: "", description: "", permissionIds: [] });
        }}
        onOk={handleCreate}
        confirmLoading={createLoading}
        okText="创建"
        cancelText="取消"
      >
        <div className="flex flex-col gap-4 py-2">
          <div>
            <label className="mb-1 block text-sm font-medium text-ink-700">角色编码</label>
            <Input
              placeholder="如: EDITOR"
              value={createForm.code}
              onChange={(e) => setCreateForm((prev) => ({ ...prev, code: e.target.value }))}
            />
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-ink-700">角色名称</label>
            <Input
              placeholder="如: 编辑员"
              value={createForm.name}
              onChange={(e) => setCreateForm((prev) => ({ ...prev, name: e.target.value }))}
            />
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-ink-700">描述</label>
            <Input
              placeholder="角色描述（可选）"
              value={createForm.description}
              onChange={(e) => setCreateForm((prev) => ({ ...prev, description: e.target.value }))}
            />
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-ink-700">权限</label>
            <Select
              mode="multiple"
              className="w-full"
              placeholder="选择权限"
              value={createForm.permissionIds}
              onChange={(val) => setCreateForm((prev) => ({ ...prev, permissionIds: val }))}
              options={permissions.map((p) => ({ label: `${p.name} (${p.code})`, value: p.id }))}
            />
          </div>
        </div>
      </Modal>

      {/* Edit Role Modal */}
      <Modal
        open={editModalOpen}
        title="编辑角色"
        onCancel={() => {
          setEditModalOpen(false);
          setEditingRole(null);
        }}
        onOk={handleEdit}
        confirmLoading={editLoading}
        okText="保存"
        cancelText="取消"
      >
        {editingRole && (
          <div className="flex flex-col gap-4 py-2">
            <div>
              <label className="mb-1 block text-sm font-medium text-ink-700">角色名称</label>
              <Input
                value={editingRole.name}
                onChange={(e) => setEditingRole((prev) => prev ? { ...prev, name: e.target.value } : null)}
              />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-ink-700">描述</label>
              <Input
                value={editingRole.description}
                onChange={(e) => setEditingRole((prev) => prev ? { ...prev, description: e.target.value } : null)}
              />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-ink-700">权限</label>
              <Select
                mode="multiple"
                className="w-full"
                placeholder="选择权限"
                value={editingRole.permissionIds}
                onChange={(val) => setEditingRole((prev) => prev ? { ...prev, permissionIds: val } : null)}
                options={permissions.map((p) => ({ label: `${p.name} (${p.code})`, value: p.id }))}
              />
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
